version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: agrotrack-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: agrotrack
      POSTGRES_USER: agrotrack
      POSTGRES_PASSWORD: agrotrack
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: agrotrack-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
volumes:
  pgdata:
  redisdata: